transforms = ["toLogical"]

# Additional includes (will appear at head)
#includes = []

# Additional raw C code (will appear after includes)
# raw = '''
# '''

[renameCalls]
"__VERIFIER_nondet"     = "__VERIFIER_nondet_int"
"nondet"                = "__VERIFIER_nondet_int"

[retype]
"TYPEOFVALUES"   = "char"
