[renameCalls]
"__VERIFIER_nondet"     = "__VERIFIER_nondet_int"
"nondet"                = "__VERIFIER_nondet_int"

[retype]
"TYPEOFVALUES"   = "char"

[main]
# Additional includes (will appear at head)
#includes = []

# Additional raw C code (will appear after includes)
rawPrelude = '''
int __VERIFIER_nondet_int() { int x; return x; }
int __VERIFIER_assume(int COND) { if (!COND) goto EXIT_main; }
'''

do = [
  "toLogical",
  "purgeTypedefs",
  "retype",
  "renameCalls"
]
