[renameCalls]
"__VERIFIER_nondet"     = "__VERIFIER_nondet_int"
"nondet"                = "__VERIFIER_nondet_int"

[retype]
"FOO"   = "short"

[main]
# Additional includes (will appear at head)
includes = ["smack.h"]

# Additional raw C code (will appear after includes)
raw = '''
extern int p(void);
'''

do = [
    "toLogical",
    "retype",
    "renameCalls"
]
