[initialize]
char = "__VERIFIER_nondet_char"
int = "__VERIFIER_nondet_int"
# Wildcard, will apply to all other declarations
"*" = "__VERIFIER_nondet_int"

[renameCalls]
"__VERIFIER_nondet"     = "__VERIFIER_nondet_int"

[retype]
"TYPEOFVALUES"   = "char"

[main]
# Additional raw C code (will appear after includes)
rawPrelude = '''
#define assert(COND) if (!(COND)) __VERIFIER_error()
'''

do = [
    "toLogical",
    "initialize",
    "renameCalls",
    "noArrays"
]